sudo: required

language: python

services:
  - docker

script:
  - pytest

before_install:
  - chmod +x ./scripts/ecr_credentials.sh
  - ./scripts/ecr_credentials.sh

after_success:
  - docker --version
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 730924386278.dkr.ecr.us-east-2.amazonaws.com
  - docker build -t hcs .
  - docker tag hcs:latest 730924386278.dkr.ecr.us-east-2.amazonaws.com/hcs:latest
  - docker push 730924386278.dkr.ecr.us-east-2.amazonaws.com/hcs:latest